version: "3.3"

services:
  go:
    build: .
    container_name: go-dev-env
    volumes:
      - type: bind
        source: "$PWD/../code/"
        target: /go/src/
    stdin_open: true
    tty: true
    command: sh
