version: "3.3"

services:
  [SERVICE_NAME]:
    build: .
    container_name: [CONTAINER_NAME]
    volumes:
      - type: bind
        source: "$PWD/../code/"
        target: /go/src/
    stdin_open: true
    tty: true
    command: zsh
